#!/usr/bin/env ruby

#!/usr/bin/env ruby

require 'optparse'
require 'fileutils'
require 'psd'

opt = OptionParser.new
params = {}
opt.on('-o out', '--out', 'Output json path') {|v| params[:out] = v }
opt.parse! ARGV

psd_path = File.expand_path(ARGV.last)
  
psd = PSD.new(psd_path)
psd.parse!

json_path = params[:out] ||
  File.join(File.dirname(psd_path),
            File.basename(psd_path, '.*') + '.json'

FileUtils.mkdir_p(File.dirname(json_path))

psd.tree.descendant_layers do |layer|
end
